services:
  - type: web
    name: budgetpal
    env: python
    region: frankfurt
    pythonVersion: 3.11.6   # <-- add this line with full version
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
